### ISSUE TITLE
script not work 

### ISSUE THREAD

**Issue by dzakki** [kucing-hitam/instagram-crash#2]
i have tried many times.. but still not work

`Traceback (most recent call last):
  File "ig-c.py", line 2, in <module>
    Hn7MS4B6n/XI6TnNGBGXMly4Ivv03OBJS+r3z31Hp+27Tu2eaPwtqw4dc+ogqUJNQ98fj5W6RJUqk0Fz/fW9n/9qVxz6pzn85OT/Jp9b276+h17aprfLHL73uzszdkbfHISTg7nm+YdMfOKj5lrjosZYMgdXoETR9X163TcjJPB3XpO49t+2PKEkRUgI16GsLBqOk3N2bdemzJJ6HjkG1rnra824prkfQ3tHcAPUC8cVSIxPLUUtnvEvOgMnehwZGjSjHkF+7SgErgJxYCemsbCAG82GQ+7XTEDNhkv2kCHDReVSiIow6ajxNY2zIDnIRvPCDYeaW3L1AO1BxHF4GaL6LoBsbZKe9hN3t5RNuL60QtDwtWtIKjZmHjbOHH7ZUNEtLPte8xk1LhrlQcBld4RviMbi4ETipuYjof1mrYzht9oxHkHwnCAK0BZ9+4MQWTzRkQvV3AQhQNnrBkrk8pmh+Z76eyD30E4B2H+DWyVarea336oy1B7ZyoLMgNWL3DaIZD6N7irrtU="))))
  File "dg", line 132, in <module>
  File "dg", line 98, in Login
KeyError: 'csrftoken'
`

**Comment by marsianinsmarsa** [comment]
? Problems
My brut no work. WTF?

**Comment by Termuxyash** [comment]
My brother not working
